{{- if .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-creds
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret | nindent 2 }}
{{- end }}
