repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.12.0
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
          - --skip-version-footer
          - --sort-values-order=file
