apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels: {{- include "mosquitto.selector" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "mosquitto.selector" . | nindent 8 }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.existingConfigMap }}
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
      {{- end }}
      {{- if or (and .Values.authentication.passwordEntries .Values.authentication.passwordFilePath) (and .Values.authorization.acls .Values.authorization.aclfilePath) }}
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum | trunc 63 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
      serviceAccountName: {{ include "mosquitto.serviceAccountName" . }}
    {{- with .Values.podSecurityContext }}
      securityContext:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
      containers:
      {{- if .Values.monitoring.sidecar.enabled }}
        - name: exporter
          image: "{{ .Values.monitoring.sidecar.image.repository }}:{{ .Values.monitoring.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.monitoring.sidecar.image.pullPolicy }}
          {{- with .Values.monitoring.sidecar.args }}
          args:
            {{ toYaml . | indent 12 | trim }}
          {{- end }}
          {{- with .Values.monitoring.sidecar.envs }}
          env:
            {{ toYaml . | indent 12| trim }}
          {{- end }}
          resources:
            {{ toYaml .Values.monitoring.sidecar.resources | indent 12 | trim }}
          ports:
            - containerPort: {{ .Values.monitoring.sidecar.port }}
              name: prometheus
              protocol: TCP
      {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.ports }}
          ports:
          {{- range $key, $value := . }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: {{ default "TCP" $value.protocol }}
          {{- end }}
        {{- end }}
          {{- with .Values.env }}
          env:
            {{ toYaml . | indent 12| trim }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.probes.liveness.tcpSocketPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.probes.readiness.tcpSocketPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
        {{- with .Values.securityContext }}
          securityContext:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
        {{- with .Values.resources }}
          resources:
            {{ toYaml . | indent 12 | trim }}
        {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.configMountPath }}
              subPath: mosquitto.conf
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
          {{- if and .Values.authentication.passwordEntries .Values.authentication.passwordFilePath }}
            - name: passwordfile
              mountPath: {{ .Values.authentication.passwordFilePath }}
              subPath: passwordfile
          {{- end }}
          {{- if and .Values.authorization.acls .Values.authorization.aclfilePath }}
            - name: aclfile
              mountPath: {{ .Values.authorization.aclfilePath }}
              subPath: aclfile
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{ toYaml . | indent 12 | trim }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ if .Values.existingConfigMap }}{{ .Values.existingConfigMap }}{{ else }}{{ include "mosquitto.fullname" . }}{{ end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "mosquitto.fullname" . }}{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if and .Values.authentication.passwordEntries .Values.authentication.passwordFilePath }}
        - name: passwordfile
          secret:
            secretName: {{ include "mosquitto.fullname" . }}
      {{- end }}
      {{- if and .Values.authorization.acls .Values.authorization.aclfilePath }}
        - name: aclfile
          secret:
            secretName: {{ include "mosquitto.fullname" . }}
      {{- end }}
      {{- with .Values.extraVolumes }}
        {{ toYaml . | indent 8 | trim }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 | trim }}
    {{- end }}
