{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "mosquitto.fullname" . }}-prometheus-exporter
  {{- with .Values.monitoring.podMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
  {{- with .Values.monitoring.podMonitor.labels }}
{{ toYaml . | indent 2 }}
  {{- end }}
spec:
  podMetricsEndpoints:
    - port: prometheus
      path: {{ .Values.monitoring.podMonitor.path }}
      interval: {{ .Values.monitoring.podMonitor.interval }}
      {{- with .Values.monitoring.podMonitor.bearerTokenFile }}
      bearerTokenFile: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.bearerTokenSecret }}
      bearerTokenSecret:
        name: {{ .name }}
        key: {{ .key }}
        {{- if hasKey . "optional" }}
        optional: {{ .optional }}
        {{- end }}
      {{- end }}
  jobLabel: {{ template "mosquitto.fullname" . }}-prometheus-exporter
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels: {{- include "mosquitto.selector" . | nindent 6 }}
{{- end }}
