apiVersion: v2
appVersion: v2.3.1
description: A Helm chart for github-exporter
home: https://github.com/githubexporter/github-exporter
name: github-exporter
type: application
sources:
  - https://github.com/githubexporter/github-exporter
maintainers:
  - name: varet80
    url: https://github.com/varet80
version: 0.0.1
